# Example Site settings

google_analytics: UA-73953230-2

header_pages:
  - index.md
  - about.md

footer: 'test' #'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
